apiVersion: v1
kind: Service
metadata:
  name: projectdevops-service
spec:
  selector:
    app: projectdevops
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
