apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectdevops-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projectdevops
  template:
    metadata:
      labels:
        app: projectdevops
    spec:
      containers:
        - name: projectdevops
          image: kimou605/projectdevops:1.0.0
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/devops_db?createDatabaseIfNotExist=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "devops_user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "devops_password"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "devops_db"
            - name: MYSQL_USER
              value: "devops_user"
            - name: MYSQL_PASSWORD
              value: "devops_password"
            - name: MYSQL_ROOT_PASSWORD
              value: "root_password"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          emptyDir: {}
